name: WakaTime Readme
on:
    schedule:
        # Runs at 12am AEST (2pm UTC)
        - cron: "00 14 * * *"
    workflow_dispatch:
jobs:
    update-readme:
        name: Update Readme with Metrics
        runs-on: ubuntu-latest
        steps:
            - uses: anmol098/waka-readme-stats@master
              with:
                  WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
                  GH_TOKEN: ${{ secrets.GH_TOKEN }}
                  SHOW_LINES_OF_CODE: true
                  SHOW_TIMEZONE: false
                  SHOW_SHORT_INFO: false
                  SHOW_LOC_CHART: false
                  SHOW_PROJECTS: false
